-- AscensionStockData.creatures part 4 of 4
-- Source: hertigservices/ascension-data (cachedata); mode conquest-of-azeroth, union fallback; data captured through 2026-09-10.
-- Generated by tools/export_stock_client.py -- regenerated on every publish, do not edit.
-- Row layout: T[entry] = { name, subname, displayId }
local T = AscensionStockData.creatures
T[11000342]={"Heart of Ascension","",354000}
T[11000343]={"Heart of Ascension","",354000}
T[11000344]={"Heart of Ascension","",354000}
T[11000345]={"Heart of Ascension","",354000}
T[11000346]={"Heart of Ascension","",354000}
T[11000347]={"Heart of Ascension","",354000}
T[11000348]={"Heart of Ascension","",354000}
T[11000428]={"Heart of Ascension","",354000}
T[11001001]={"Void Shardling","",78509}
