name: Update public database website
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  catalog:
    uses: hertigservices/Ascension_preservation/.github/workflows/ascension-db.yml@b22dbf4f28b8163f384feab81387fc3f2027b464
    with:
      source_ref: b22dbf4f28b8163f384feab81387fc3f2027b464
