name: Update public database website
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  catalog:
    uses: hertigservices/Ascension_preservation/.github/workflows/ascension-db.yml@8a67e906db61f6e31bd1b7596fae2bc59fffc869
    with:
      source_ref: 8a67e906db61f6e31bd1b7596fae2bc59fffc869
